[beanstalk-example]
provider = "beanstalk"
domain = ""
login = ""
password = ""

[gitlabhq-example]
provider = "gitlabhq"
endpoint = ""
private_token = ""

[bitbucket-example]
provider = "bitbucket"
username = ""
password = ""

[github-user-example]
provider = "github"
username = ""
password = ""

[github-org-example]
provider = "github"
username = ""
password = ""
org = ""